version: 2.1

jobs:
  first-circle-ci-job:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
         command: |
            echo Its my first CircleCI Job.

workflows:
  first-workflow:
    jobs:
      - first-circle-ci-job
