version: 2.1

jobs:
  first-circle-ci-job:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run:
         command: |
            echo Its my first CircleCI Job.
            echo Its Second job execution >> artifact.txt
            ls -la # Command to list all files in current directory including newly created
      - store_artifacts:
          path: /home/circleci/project/artifact.txt
          destination: artifactFile

workflows:
  first-workflow:
    jobs:
      - first-circle-ci-job
      