version: 2.1

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.


jobs:
  first-circle-ci-job:
    executor: win/default # executor type
    steps:
      - checkout
      - run:
         command: |
            sudo apt update -y

workflows:
  first-workflow:
    jobs:
      - first-circle-ci-job
