version: 2.1

jobs:
  first-circle-ci-job:
    docker:
      # Primary container image where all steps run.
      - image: circleci/openjdk:8u171-jdk
      # Secondary container image on common network. 
      - image: mongo:2.6.8-jessie
    steps:
      - checkout
      - run:
         command: |
            echo Its my first CircleCI Job.
      # Below command will execute in openjdk container
      # and can access mongo on localhost
      - run: sleep 5 && nc -vz localhost 27017

workflows:
  first-workflow:
    jobs:
      - first-circle-ci-job
