version: 2.1

jobs:
  job-to-demonstrate-environment:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run:
         command: |            
            # 1 Type of ENV : Environment variable for a single command shell             
            echo "Value for variable ENV_INSIDE_STEP is :: "$ENV_INSIDE_STEP
            
            # 2 Type of ENV : Environment variable for whole JOB 
            echo "Value for variable ENV_INSIDE_JOB is :: "$ENV_INSIDE_JOB
            
            # 3 Env Variable -- Special build variables
            echo "CIRCLE_BRANCH NAME IS :: $CIRCLE_BRANCH"
            
            # 4th Type of ENV : Environment variable from Context             
            echo "Value for context variable is :: "$demoKey
         environment:
           ENV_INSIDE_STEP: I am defined as env variable in run.
    environment:
       ENV_INSIDE_JOB: I am defined as env variable in JOB

  first-circle-ci-job:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run:
         command: |
            echo Its my first CircleCI Job.
            echo Its Second job execution >> artifact.txt
            ls -la # Command to list all files in current directory including newly created
      - store_artifacts:
          path: /home/circleci/project/artifact.txt
          destination: artifactFile

  second-circle-ci-job:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run:
         command: |
            curl -H "Circle-Token: " https://circleci.com/api/v1.1/project/github/rishikhuranasufi/$CIRCLE_PROJECT_REPONAME/latest/artifacts \
               | grep -o 'https://[^"]*' \
               | wget --verbose --header "Circle-Token: " --input-file -
            cat artifactFile  

workflows:
  first-workflow:
    jobs:
      - first-circle-ci-job
      - second-circle-ci-job
  workflow-to-demonstrate-environment:    
    jobs:
      - job-to-demonstrate-environment:
          context:
            - my-context
            - another-context
      